default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: myuser
  password: mypassword
  database: mydatabase

development:
  <<: *default
